workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - ios/Pods
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
